### ISSUE TITLE
get rid of tcl files

### ISSUE THREAD

**Issue by porres** [porres/pd-knob#1]
turn them into .c files and make it part of the object

@timothyschoen please clone this repository and send PRs here, if you help me with this issue I can do the rest ;)

**Comment by porres** [comment]
@timothyschoen please clone this repository and send PRs here, if you help me with this issue I can do the rest ;)

**Comment by porres** [comment]
@timothyschoen note that I want to get rd of all 'iemguis' dependency! Just like we did to numbox~

**Comment by porres** [comment]
@timothyschoen I would also like to simplify and change the properties, like getting rid of 'label' and make other changes we also did for numbox~ but first let's just get rid of the tcl files

**Comment by timothyschoen** [comment]
I see that the .tcl files are just the dialogs, we do want to keep the dialog right? So just put the dialogs in a separate C file?

I'll do it and send a PR, but just so you know, all really I do is run the tcl file through [text to C string converter](https://tomeko.net/online_tools/cpp_text_escape.php?lang=en)

Let me know if there are any other things that need to be fixed!
