### ISSUE TITLE
properties

### ISSUE THREAD

**Issue by porres** [porres/pd-knob#15]
remove 'arc' from colors

make it 'arc width' a toggled box

include toggle box for discrete mode

rename and really detach from "iemguis properties" code because it's conflicting to other iemguis' properties.

@timothyschoen

**Comment by porres** [comment]
@timothyschoen note we're also passing back and forth way more arguments to the properties windows and back than we need. We now only have about 15 arguments...

**Comment by porres** [comment]
we should have a dropmenu for log and exp mode, exp mode would activate a number box for the factor.

**Comment by porres** [comment]
we should have a dropmenu for log and exp mode, exp mode would activate a number box for the factor. A place I've seen something like this is in deken preferences

![Screen Shot 2023-04-04 at 14 06 05](https://user-images.githubusercontent.com/5360142/229866116-8a0a2d96-9893-43d4-96a6-b704c8c860fd.png)

**Comment by timothyschoen** [comment]
<img width="644" alt="Screenshot 2023-04-05 at 00 42 06" src="https://user-images.githubusercontent.com/44585538/229938208-5f7a3272-a3db-48f8-886f-1cd45722b553.png">

Almost there...

**Comment by porres** [comment]
@timothyschoen while we're at it, it seems weird that size is all by itself on top, it should be with the other more general ones, so maybe bring up all of what's in 'parameters' on top over there with it, then we have more specialized groups below

**Comment by timothyschoen** [comment]
I think these are all done!

**Comment by porres** [comment]
looking great, what I first thought though was that the 'parameters' section would come first on top, and without the 'parameters' header at all... just like before we simply had 'size' without any section header. My idea was to bring all the others to the top, then a 2nd section would be the range, with the parameters.

As for the parameters, I think we can swap the positions of 'initial value' and 'size', making size come first.

as for the log/exp, my idea is that we don't have a 'normal' mode, just 'exp' and 'log', the 'normal mode' would be 'exp 1' (the default setting), which means 'linear'

**Comment by porres** [comment]
for some reason the changes to properties, specially colors, don't happen right away when you click to select them... this is how it usually goes in Vanilla, at least for mac, I guess linux/window is different

**Comment by porres** [comment]
> for some reason the changes to properties, specially colors, don't happen right away when you click to select them... this is how it usually goes in Vanilla, at least for mac, I guess linux/window is different

it's how numbox~ works btw

**Comment by timothyschoen** [comment]
> looking great, what I first thought though was that the 'parameters' section would come first on top, and without the 'parameters' header at all... just like before we simply had 'size' without any section header. My idea was to bring all the others to the top, then a 2nd section would be the range, with the parameters.
> 
> As for the parameters, I think we can swap the positions of 'initial value' and 'size', making size come first.
> 
> as for the log/exp, my idea is that we don't have a 'normal' mode, just 'exp' and 'log', the 'normal mode' would be 'exp 1' (the default setting), which means 'linear'

I can move that stuff around, no problem!

Not sure of it's insightful to have "exp 1" to indicate normal mode, isn't a normal mode button more clear? Your call though.

I'll take a look at live updating colours, but I have no idea how that works, we'll see.

**Comment by porres** [comment]
@timothyschoen the "undo" part still gets a list of arguments that's way too much more than needed

would you be able to clean that up and get the same length of parameters from our argument list and what we actually use from properties? It's about 15, not 23!

**Comment by porres** [comment]
@timothyschoen 'compose color' gives an error that blows up Pd for both backcground and front settings

**Comment by porres** [comment]
- 'ticks' and 'discrete' are related, they could be in a subgroup
- same with angular range and offset

**Comment by porres** [comment]
yes, but i'd like a commented file so I can understand what's going on in  '.h' wink wink

**Comment by porres** [comment]
@timothyschoen I just added the arc background color so you can add that to the window as well... besides working the send and receive symbols

**Comment by porres** [comment]
oh, we also need a tick box for the outline now

**Comment by porres** [comment]
I removed the expmode arg, it is not needed, replaced it by the outline one, I need help now figuring the tcl tk part that deals with setting the exp value, right now they're not coming through

**Comment by timothyschoen** [comment]
I'll be able to fix all of these (working on it, I'll hopefully send a PR later), except expanding dollar signs, since I'm not very good at that part of Pd. I don't understand it well enough to be able to implement it. I think it would be better to handle that from C anyway, not from tcl/tk.

**Comment by timothyschoen** [comment]
Also, I'm not sure what you want to do with logmode, I expmode is still implemented in C, so I'm not sure what to do with that.

**Comment by porres** [comment]
> I think it would be better to handle that from C anyway, not from tcl/tk.

this needs to be done from the tcl/tk side when setting the send and receive names as the $ character needs to be escaped, and other characters also could and should be escaped by the way... I can help you figure this out, I just tried it myself and it failed and I couldn't understand

**Comment by porres** [comment]
> I'm not sure what you want to do with logmode

sorry I messed with the way you were doing this, but we now need to figure out a new way to set the linear, log and exp mode.

**Comment by timothyschoen** [comment]
> > I think it would be better to handle that from C anyway, not from tcl/tk.
> 
> this needs to be done from the tcl/tk side when setting the send and receive names as the $ character needs to be escaped, and other characters also could and should be escaped by the way... I can help you figure this out, I just tried it myself and it failed and I couldn't understand

We should probably try to steal this from the iemguis, I might have accidentally removed it

**Comment by porres** [comment]
yeah, it's in the iemguis code somewhere, I can point you to it, hold on

**Comment by porres** [comment]
and right now every time I try to set to linear mode in properties it doesn't work...

**Comment by porres** [comment]
cant find the conde in iemguis, but here's how it's dealt with in the note object

https://github.com/porres/pd-else/blob/master/Classes/Source/note.c#L1581 

https://github.com/porres/pd-else/blob/master/Classes/Source/note.c#L1618 

https://github.com/porres/pd-else/blob/master/Classes/Source/note.c#L1630

**Comment by porres** [comment]
found this in iemguis https://github.com/pure-data/pure-data/blob/master/tcl/dialog_iemgui.tcl#L262

**Comment by porres** [comment]
and this https://github.com/pure-data/pure-data/blob/master/tcl/dialog_iemgui.tcl#L248

**Comment by porres** [comment]
closing this, but not really done with it
