### ISSUE TITLE
can't delete the object...

### ISSUE THREAD

**Issue by porres** [porres/pd-knob#3]

**Comment by timothyschoen** [comment]
hmm I can delete it here, using pd-0.53-0

**Comment by porres** [comment]
> hmm I can delete it here, using pd-0.53-0

hmm, seems I can't in 0.53-2

**Comment by porres** [comment]
but yeah, I can delete it in 0.53-0 :) 

anyway, time to finally work on this. I see I opened the request over 3 years ago already, we waited enough time :)

**Comment by timothyschoen** [comment]
Might be because the t_iemgui class layout has changed between Pd versions? So if you compile an object against a different version than you run it in, it wouldn't work. Not sure if that's what's going on, but it could be?

**Comment by porres** [comment]
I thought I had compiled against current master... let me see...

**Comment by porres** [comment]
yup, compiled against current master, it doesn't work. I can't displace it either by the way

**Comment by porres** [comment]
but if I have 0.53-0, it works...

**Comment by porres** [comment]
I mean, if I open the compiled object (compiled against current) with the older version it works
