### ISSUE TITLE
make 'init' like in [numbox~] (have us set the value)

### ISSUE THREAD

**Issue by porres** [porres/pd-knob#7]
@timothyschoen  I guess after this we're "done", but I want to remove the iemgui dependencies and work more on it. Can you work a bit on this too?

**Comment by timothyschoen** [comment]
I'll fix the initial value, could you fix the iemgui deps?

**Comment by porres** [comment]
Yup

**Comment by porres** [comment]
Gonna wait for your changes though

**Comment by porres** [comment]
> Gonna wait for your changes though

@timothyschoen I'm trying to fix a few things before

**Comment by porres** [comment]
@timothyschoen I have things cleanup and fixed... All you need to do is work on the properties for loading and setting the 'init' value
